./dut_mycore/mycore.v
./dut_mycore/reg/reg_PC.v
./dut_mycore/reg/reg_R.v
./dut_mycore/controller/decoder.v
./dut_mycore/controller/controller.v
./dut_mycore/fu/shifter.v
./dut_mycore/fu/multiplier.v
./dut_mycore/fu/alu.v
./dut_mycore/fu/lsu.v
./dut_mycore/fu/adder.v
./dut_mycore/fu/divider.v
./test_bench/mycore_if.sv
./test_bench/mycore_pkg.sv
./test_bench/test_bench.sv
./test_bench/env/env.sv
./test_bench/env/agent.sv
./test_bench/seq/sequence.sv
./test_bench/seq/sequence_item.sv
./test_bench/agent/sequencer.sv
./test_bench/agent/driver.sv
./test_bench/agent/monitor.sv
./test_bench/test/test.sv
